version: '3'
services:
  backend:
    build: .
    ports:
      - "8088:8088"
    command: pipenv run black
    tty: true
    volumes:
      - ./flask:/var/www/flask
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./log/uwsgi:/var/log/uwsgi
      - ./log/nginx:/var/log/nginx
      - backend-venv:/var/www/flask/.venv
    restart: unless-stopped
    env_file:
      - ../settings.env
      - ../settings.dev.env
    environment:
      - "PIPENV_VENV_IN_PROJECT=1"

volumes:
  db-data:
  backend-venv:
